#!/bin/bash
#BSUB -n 1
#BSUB -R "span[ptile=16]"
#BSUB -oo OUTPUT/ompss-ee_%J.out
#BSUB -eo OUTPUT/ompss-ee_%J.err
#BSUB -x # Exclusive use
#BSUB -J ompss-ee
#BSUB -W 00:15

NCHUNKS="8 16 32 64 128 256 512 1024 2048"
for nc in $NCHUNKS 
do 
  ./stream_triad-$nc
done
